version: "3.8"

services: 
  # NGINX
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    links:
      - vue
      - server
    depends_on:
      - vue
      - server
    ports:
      - "8000:80"
    volumes: 
      - ./nginx:/etc/nginx/conf.d

  # VUE
  vue:
    build: ./client
    container_name: vue
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src
    expose: 
      - 8080

  # SERVER
  server:
    build: ./server
    container_name: server
    restart: always
    expose:
      - 5000
    volumes:
      - ./server:/usr/src

  # IPFS
  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs
    restart: always
    ports:
      - "4001:4001"