version "3.8"

services:
  # NGINX
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    links:
      - server
      - react
    depends_on:
      - server
      - react
    ports:
      - "8000:80"
    volumes: 
      - ./nginx:/etc/nginx/conf.d

  # REACT
  react:
    container_name: react
    build: ./client
    restart: always
    volumes:
      - ./client:/usr/src
    expose: 
      - 3000